services:
  portainer-agent:
    container_name: portainer-agent
    image: portainer/agent:latest
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    depends_on:
      - portainer
    restart: unless-stopped
    environment:
      TZ: Asia/Kolkata
    networks:
      - portainer

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      TZ: Asia/Kolkata
    networks:
      - portainer
    restart: unless-stopped

networks:
  portainer:
    driver: bridge

volumes:
  portainer_data:
    name: portainer_data
